sudo: false
language: python
python:
  - "2.7"
branches:
  only:
    - staging
    - master

install:
  # for fontmake
  - git clone https://github.com/googlei18n/fontmake.git
  - cd fontmake
  - pip install -r requirements.txt
  - python setup.py install
  - cd ..
  # for notodiff
  - git clone https://github.com/googlei18n/nototools.git
  - cd nototools
  - python setup.py install
  - cd ..
  # for fontdiff
  - wget https://github.com/googlei18n/fontdiff/releases/download/v0.1.1/fontdiff-linux.zip
  - unzip fontdiff-linux.zip
  - mv fontdiff-linux/fontdiff .

script:
  - bash ./build_travis.sh
